exclude: '^docs/|^media/|/migrations/|devcontainer.json|\.venv/|venv/|node_modules/'
default_stages: [commit]

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-json
        files: \.(json|jsonc)$
      - id: check-toml
        files: \.(toml|lock)$
      - id: check-xml
        files: \.xml$
      - id: check-yaml
        files: \.(yaml|yml)$
      - id: debug-statements
        files: \.py$
      - id: check-builtin-literals
        files: \.py$
      - id: check-case-conflict
      - id: check-docstring-first
        files: \.py$
      - id: detect-private-key

  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.20.0'
    hooks:
      - id: django-upgrade
        args: ['--target-version', '5.0']
        files: \.py$

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      # Linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: \.py$
      # Formatter
      - id: ruff-format
        files: \.py$

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django
        files: ^footycollect/.*\.html$
        args: [--reformat, --quiet, --max-attribute-length=120]
      - id: djlint-django
        files: ^footycollect/.*\.html$
        args: [--quiet, --max-attribute-length=120]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
